### PR TITLE
Responsive Banner

### PR DESCRIPTION
**Pull request by dfosco**
Just a few adjustments — but wait for [Responsive Homepage & Header](https://github.com/vtex-apps/theme/pull/113) to be merged first!

### CODE REVIEW

**Comment by brenoc** [comment]
@dfosco There's a merge commit in this branch, I think maybe you're rebasing it the wrong way.

**Comment by dfosco** [comment]
@brenoc Probably :/

**Comment by dfosco** [comment]
@brenoc Should we do a `rebase -i` to fix it?

**Comment by brenoc** [comment]
@dfosco yep!

**Comment by dfosco** [comment]
@brenoc `rebase -i` is done, needs review now :smile:

**Pull request merged**
